-- Tracks each individual survey email attempt (project + survey + developer),
-- so per-developer send cadence can be enforced without touching `project` or `survey`.
CREATE TABLE IF NOT EXISTS public.survey_recipient (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id integer NOT NULL REFERENCES public.survey(id),
  project_id integer NOT NULL REFERENCES public.project(id),
  user_id integer NOT NULL REFERENCES public."User"(id),
  email character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'skipped', 'failed')),
  skip_reason character varying,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
