-- Collapse per-metric columns into a single `metrics` jsonb column on all 4
-- tool metrics tables. Existing rows keep their id/snapshot_id but lose their
-- old per-column values - `metrics` defaults to '{}' until the next sync
-- repopulates it. Idempotent: safe to re-run on a partially-migrated DB.

ALTER TABLE public.versioncontrolmetrics
  DROP COLUMN IF EXISTS issues_closed_per_week,
  DROP COLUMN IF EXISTS issue_cycle_time_avg_days,
  DROP COLUMN IF EXISTS pr_review_coverage_percent,
  DROP COLUMN IF EXISTS review_per_pr_avg,
  DROP COLUMN IF EXISTS self_merged_pr_rate_percent,
  DROP COLUMN IF EXISTS time_to_first_review_avg_hours,
  DROP COLUMN IF EXISTS files_modified_gte_10_times,
  DROP COLUMN IF EXISTS files_modified_by_gte_3_people,
  DROP COLUMN IF EXISTS commit_with_issue_ref_percent,
  DROP COLUMN IF EXISTS commit_with_body_percent,
  DROP COLUMN IF EXISTS commit_following_convention_percent,
  DROP COLUMN IF EXISTS stale_pr_count,
  DROP COLUMN IF EXISTS long_lived_branches_count,
  DROP COLUMN IF EXISTS pr_revert_rate_percent,
  DROP COLUMN IF EXISTS bus_factor,
  DROP COLUMN IF EXISTS active_contributions_per_week,
  DROP COLUMN IF EXISTS review_network_density,
  DROP COLUMN IF EXISTS dependency_update_lag_avg_days,
  DROP COLUMN IF EXISTS health_score,
  ADD COLUMN IF NOT EXISTS metrics jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.cicdmetrics
  DROP COLUMN IF EXISTS pipeline_success_rate_percent,
  DROP COLUMN IF EXISTS avg_pipeline_duration_minutes,
  DROP COLUMN IF EXISTS flaky_test_count,
  DROP COLUMN IF EXISTS test_coverage_percent,
  DROP COLUMN IF EXISTS test_failure_rate_percent,
  DROP COLUMN IF EXISTS avg_pipeline_runs_per_pr,
  DROP COLUMN IF EXISTS deployments_per_week,
  DROP COLUMN IF EXISTS deployment_failure_rate_percent,
  DROP COLUMN IF EXISTS mttr_hours,
  DROP COLUMN IF EXISTS time_to_prod_hours,
  ADD COLUMN IF NOT EXISTS metrics jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.codequalitymetrics
  DROP COLUMN IF EXISTS technical_debt_ratio,
  DROP COLUMN IF EXISTS technical_debt_minutes,
  DROP COLUMN IF EXISTS maintainability_rating,
  DROP COLUMN IF EXISTS code_smells,
  DROP COLUMN IF EXISTS duplicated_lines_density,
  DROP COLUMN IF EXISTS bugs,
  DROP COLUMN IF EXISTS reliability_rating,
  DROP COLUMN IF EXISTS vulnerabilities,
  DROP COLUMN IF EXISTS security_rating,
  DROP COLUMN IF EXISTS critical_vulnerabilities,
  DROP COLUMN IF EXISTS high_vulnerabilities,
  DROP COLUMN IF EXISTS coverage,
  DROP COLUMN IF EXISTS lines_of_code,
  DROP COLUMN IF EXISTS quality_gate_status,
  DROP COLUMN IF EXISTS new_bugs,
  DROP COLUMN IF EXISTS new_vulnerabilities,
  DROP COLUMN IF EXISTS new_code_smells,
  DROP COLUMN IF EXISTS new_coverage,
  DROP COLUMN IF EXISTS new_duplicated_lines_density,
  DROP COLUMN IF EXISTS new_technical_debt,
  ADD COLUMN IF NOT EXISTS metrics jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.projectmanagementmetrics
  DROP COLUMN IF EXISTS sprint_completion_rate,
  DROP COLUMN IF EXISTS issue_cycle_time_avg_days,
  DROP COLUMN IF EXISTS throughput_per_week,
  DROP COLUMN IF EXISTS carryover_rate,
  DROP COLUMN IF EXISTS scope_creep_rate,
  DROP COLUMN IF EXISTS estimation_accuracy,
  DROP COLUMN IF EXISTS blocked_items_count,
  DROP COLUMN IF EXISTS blocked_items_avg_age_days,
  DROP COLUMN IF EXISTS overdue_items_count,
  DROP COLUMN IF EXISTS lead_time_avg_days,
  DROP COLUMN IF EXISTS lead_time_median_days,
  DROP COLUMN IF EXISTS lead_time_p95_days,
  DROP COLUMN IF EXISTS lead_time_variance,
  DROP COLUMN IF EXISTS spillover_ratio,
  DROP COLUMN IF EXISTS story_point_spillover,
  DROP COLUMN IF EXISTS consecutive_spillover_count,
  DROP COLUMN IF EXISTS carryover_avg_age_days,
  DROP COLUMN IF EXISTS blocked_ticket_percent,
  DROP COLUMN IF EXISTS avg_blocked_duration_days,
  DROP COLUMN IF EXISTS max_blocked_duration_days,
  DROP COLUMN IF EXISTS blocked_reentry_count,
  DROP COLUMN IF EXISTS mid_sprint_additions,
  DROP COLUMN IF EXISTS scope_churn_ratio,
  DROP COLUMN IF EXISTS priority_change_count,
  DROP COLUMN IF EXISTS removed_scope_ratio,
  DROP COLUMN IF EXISTS in_progress_avg_age_days,
  DROP COLUMN IF EXISTS stale_ticket_ratio,
  DROP COLUMN IF EXISTS state_movement_count,
  DROP COLUMN IF EXISTS health_score,
  ADD COLUMN IF NOT EXISTS metrics jsonb NOT NULL DEFAULT '{}'::jsonb;
